skeleton/src/Entity/UserSecurity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserSecurityRepository")
 */
class UserSecurity implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $usercode;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsercode(): ?string
    {
        return $this->usercode;
    }

    public function setUsercode(string $usercode): self
    {
        $this->usercode = $usercode;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->usercode;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        // not needed for apps that do not check user passwords
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed for apps that do not check user passwords
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

skeleton/templates/admin.html.twig
{#page for administrator panel#}
{% extends 'base.html.twig' %}

{% block body %}
<h1>Panneau administrateur</h1>

<nav>
    <a href="{{ path('user_by_admin') }}">entrer un nouvel eleve</a>
</nav>
    {{ form(filter) }}
<table>
    <tr>
        <th></th>
        <th></th>
        <th>id</th>
        <th>nom</th>
        <th>prenom</th>
        <th>mot de passe</th>
        <th>code utilisateur</th>
        <th>id_rank</th>
    </tr>
    {%if lastname is empty  %}
    {% for i in user  %}
    <tr>
        <td><a href="{{ path('remove_user',{'id': i.id }) }}"> suprimer </a></td>
        <td><a href="{{ path('update_user',{'id': i.id }) }}"> modifier</a></td>
                <td>{{ i.id }}</td>
                <td>{{ i.lastname }}</td>
                <td>{{ i.firstname }}</td>
                <td>{{ i.password }}</td>
                <td>{{ i.usercode }}</td>
                <td>{{ i.idrank }}</td>
            </tr>


        {% endfor %}
    {% endif %}
    {% if lastname is not empty  %}
    {% for i in user  if i.lastname == lastname %}
        <tr>
            <td><a href="{{ path('remove_user',{'id': i.id }) }}"> suprimer </a></td>
            <td><a href="{{ path('update_user',{'id': i.id }) }}"> modifier</a></td>
            <td>{{ i.id }}</td>
            <td>{{ i.lastname }}</td>
            <td>{{ i.firstname }}</td>
            <td>{{ i.password }}</td>
            <td>{{ i.usercode }}</td>
            <td>{{ i.idrank }}</td>
        </tr>


    {% endfor %}
    {% endif %}


</table>
{% endblock %}

skeleton/templates/base.html.twig
{# twig for base model#}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}Groupe Scolaire Kiesistpa{% endblock %}</title>
    <meta content="width=device-width,
    initial-scale=1" name="viewport"/>
    <meta name="description" content="groupe scolaire kiesistpa">
    <meta name="keywords" content="kiesistpa, groupe scolaire, parents, enfant">
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset("css/style.css") }}">
    {% endblock %}
</head>
<body>

    <header>{% block header %}
            <h1>Groupe Scolaire Kiésistpa</h1>
            {% if is_granted("IS_AUTHENTICATED_FULLY") %}
                <p> <span>Bonjour, {% if is_granted('ROLE_SUPERADMIN') %}Directeur {% elseif is_granted("ROLE_ADMIN") %}Proffesseur {% else %}Parents de{% endif %} {{ app.user.lastname }} {{ app.user.firstname }}</span> <a  class="deconnection" href=" {{ logout_path('main') }} ">Déconection</a></p>
            {% endif %}
            {% endblock %}
    </header>
    <main>
        <aside>
    {% block body %}



    {% block javascripts %}{% endblock %}
{% endblock %}</aside>
    </main>
<footer></footer>
</body>
</html>

skeleton/templates/home.html.twig
{# the home page to start the site #}
{% extends 'base.html.twig' %}




    {% block header %}
            <h1>Groupe Scolaire Kiésitpa</h1>
            <div class="formlog">
                <form  action="{{ path('login') }}" method="post">

                    <div class="connection"><label for="usercode">code utilisateur : </label>
                        <input class="" type="text" id="usercode" name="_username" value="{{ last_username }}"></div>

                    <div class="connection pass">
                        <label for="password">mot de passe : </label>
                        <input type="password" id="password" name="_password">
                    </div>

                    <button class="buttonradius" type="submit">connection</button>
                </form>
            </div>
            {% if error %}
                <div class="left" id="error" >Code utilisateur ou mot de passe incorect</div>
            {% endif %}

        <a  class="mdpo" href="{{ path('reset') }}">mot de passe oublié</a>

    {% endblock %}

{% block body %}
    <p class="padding">Bienvenus les parents,<br>
        Ce site vous permez de voir les notes de votre enfant dans les differentes matieres,<br>
        ainsi q'un espace de messagerie privée pour pouvoir communiquer avec le profeseur de votre enfant.<br></p>

    <script>
        {% for message in app.flashes('success') %}
        alert('{{ message }}');
        {% endfor %}
        

    </script>

{% endblock %}

skeleton/templates/maildeleteaccount.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>supression de votre compte</title>
</head>
<body>
<p>
    Bonjour, <br>
    Cliquez sur ce lien pour supprimer votre compte.

    <a href="{{absolute_url(path('delete_account', {'id': user.id, 'token': user.token}))}}">pour supprimer votre compte </a><br><br>

    Attention toute suppression de compte est definitive.
</p>
</body>
</html>

skeleton/templates/skill.html.twig
{#page for skill panel#}
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Panneau administrateur</h1>

    <nav>
        <a href="{{ path('create_skill') }}">entrer une nouvelle compétence</a>
    </nav>
    <table>
        <tr>
            <th></th>
            <th></th>
            <th>id</th>
            <th>compétence</th>

        </tr>
        {% for i in skill %}
            <tr>
                <td><a href="{{ path('delete_skill',{'id': i.id }) }}"> suprimer </a></td>
                <td><a href="{{ path('update_skill',{'id': i.id }) }}"> modifier</a></td>
                <td>{{ i.id }}</td>
                <td>{{ i.skill }}</td>



        {% endfor %}
    </table>
{% endblock %}

skeleton/templates/updatecomment.html.twig
{# page for fill in a form  for create a new student#}
{% extends 'base.html.twig' %}

{% block body %}
    <h1> Administrateur : modifier le message</h1>
    <a class="buttonnav" href="{{ path('admin') }}"> retour au panneaus des utilisateurs</a>
    <div class="textform">

                {{ form(comment) }}
           </div>
{% endblock %}

skeleton/templates/user.html.twig
{#page for administrator panel#}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/style.css") }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

{% endblock %}


{% block body %}


    {% if   app.user.usercode  == usercode %}
       <h1> Notes de l'élèves : {{ nom }} {{ prenom }}</h1>

        <div id="moyenne">
        <table id="averagegrade">
        <tr>
            <th class="avg">Matières</th>
            <th class="avg">Moyennes</th>
        </tr>

       {% for key, grade in gradus %}
           <tr>
               <td ><a  class="skill" id="{{ grade.id }}" href="{{ path("total_grades",{"lastname":nom ,'firstname':prenom,'selectskill': grade.skill}) }}" >{{ grade.skill }}</a></td>
              <td>{{ grade[1] | round(1,'floor')}}</td>
           </tr>


       {% endfor %}

 </table>
        <div id="graphic"><canvas id="myChart" ></canvas></div>
        </div>


        <div class="textform">{{ form(formCom) }} </div>
    <div id="comment-main-box">

        <div id="comment-title" >Correspondance Professeur/Parent</div>

        {% for comment in comments  %}
            {% if app.user.id == comment.receiver.id or app.user.id == comment.sender.id %}
            <h5>posté le {{ comment.date }} par {% if app.user.id == comment.sender.id %} les parents de {% else %} le professeur {% endif %}    {{ comment.sender.lastname }} {{ comment.sender.firstname }}</h5>
            <p class="commentaire">{{ comment.comment | nl2br }}</p>
                {% if app.user.id == comment.sender.id %}
                    <a class="buttonnav" href="{{ path("delete_user_comment",{'id':comment.id,'lastname': nom,"firstname":prenom}) }}">supprimer</a>
                    <a  class="buttonnav" href="{{ path("update_user_comment",{'id':comment.id,'lastname': nom,"firstname":prenom}) }}">modifier</a>
                {% endif %}

            {% endif %}
        {% endfor %}


    </div>
        <a class="buttonnav margin" href="{{ path("delete_mail",{"id":app.user.id}) }}">supprimer le compte</a>

        <script  src="{{ asset("js/Axios.js") }}"></script>


    <script type="text/javascript">

        {% for message in app.flashes('delete') %}
        alert('{{ message }}');
        document.location.href= "/logout";
        {% endfor %}



        function onclickdivskill(event){
            event.preventDefault();


            axios.get('/user/totalgrades/'+this.getAttribute('id')+'/{{ nom }}/{{ prenom }}')
                .then(function (response) {


                    console.log(response);
                    skills = response.data.skills;
                    grades = response.data.grades;
                    var ctx = document.getElementById('myChart').getContext('2d');

                    var myLineChart = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: skills,
                            datasets: [{
                                data: grades,
                                label: skills[0],
                                borderColor: "#3e95cd",
                                fill: false,

                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero:true,
                                        max: 20
                                    }
                                }],
                                xAxes: [{
                                    display: false
                                }]
                            }
                        }
                    });
                })
                .catch(function (error) {
                    console.log(error);
                });
        }

        document.querySelectorAll('a.skill').forEach(function (a) {
            a.addEventListener("click",onclickdivskill)
        });



        var skills = [];
        var grades = [];
        var elt = {{ objgrade |  raw  }}
        console.log(elt);

        for(let i =0;i<elt.length;i++){

         var skill = elt[i].skill;
         skills.push(skill);

         var grade = (elt[i][1]);
         grades.push(grade)

        }

 console.log(skills);
        console.log(grades);

        var ctx = document.getElementById('myChart').getContext('2d');

            var chart = new Chart(ctx, {

                type: 'radar',

                data: {
                    labels: skills,
                    datasets: [{
                        label: 'note',

                        backgroundColor: "transparent",
                        borderColor: 'rgb(0,0,255)',
                        data: grades
                    }]
                },

                options : {
                    scale: {

                        ticks: {
                            beginAtZero: true,
                            min: 0,
                            max: 20,
                            stepSize: 2,
                            lineHeight: 2
                        },
                        pointLabels: {
                            fontSize: 12
                        }
                    },
                    legend: {
                        display: false
                    },
                }

            });
    </script>
    {% else %}
    <h1>vous n'avez pas acces a cette utilisateur</h1>
    {% endif %}
{% endblock %}